sudo: required
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # to install and update kubectl insidee our Travis env.
  - gcloud auth activate-service-account --key-file service-accout.json
  # to tell the SDK who we are, we have to give it access to our account, we have it activate service account
  # and create the file with the credintials 