sudo: required
services:
  - docker
env:
  global:
    - SHA:$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  #to decrypt the json file that has the service account info
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # to install and update kubectl insidee our Travis env.
  - gcloud auth activate-service-account --key-file service-account.json
  # to tell the SDK who we are, we have to give it access to our account, we have it activate service account
  # and create the file with the credintials 
  - gcloud config set project multi-k8s-260020
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t sammour1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=ture USERNAME/docker-react npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master